name: Backend CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  basic-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js v22.11.0
        uses: actions/setup-node@v3
        with:
          node-version: "v22.11.0"
          cache: "pnpm"
          cache-dependency-path: backend/pnpm-lock.yaml

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install backend dependencies with pnpm
        run: pnpm install --frozen-lockfile
        working-directory: backend
      - name: Basic check - Workflow completed
        run: echo "Backend basic CI workflow completed successfully!"
