name: Frontend Basic CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js v22.11.0
        uses: actions/setup-node@v3
        with:
          node-version: "v22.11.0"
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml
      - name: Install frontend dependencies with pnpm
        run: pnpm install --frozen-lockfile
        working-directory: frontend
      - name: Run Next.js build
        run: pnpm run build
        working-directory: frontend
      - name: Basic check - Frontend workflow completed
        run: echo "Frontend basic CI workflow completed successfully! Next.js build passed."
